server:
  port: 8101
spring:
  application:
    name: employee-service
  cloud:
    loadbalancer:
      ribbon:
        eureka:
          enabled: true
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:h2:mem:employeedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
