server:
  port: 8082

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        loggerLevel: full

# Security (optional customization)
jwt:
  secret: secretkey123
  expirationMs: 3600000

logging:
  level:
    org.springframework.web: DEBUG
    com.yourpackage.employeeservice: DEBUG
