server:
  port: 8001

spring:
  application:
    name: login-service
  cloud:
    loadbalancer:
      ribbon:
        eureka:
          enabled: true
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:h2:mem:logindb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

resilience4j.circuitbreaker:
  instances:
    employeeService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureThresholdRate: 50
      waitDurationInOpenState: 10000
